services:
  tiktok-server:
    build: .
    environment:
      - NUM_SESSIONS=${NUM_SESSIONS:-5}
      - TIKTOK_BROWSER=${TIKTOK_BROWSER:-chromium}
      - TIKTOK_API_PORT=${TIKTOK_API_PORT:-8080}
    ports:
      - "${TIKTOK_API_PORT}:${TIKTOK_API_PORT}"
